---
title: "demo"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{demo}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(brap)
```

Let's create some simulated data. We'll start with a fake contact matrix with several groups:

```{r fake-data}
n_groups <- 10
contact_matrix <- matrix(
  runif(n_groups ^ 2, 5, 8),
  n_groups,
  n_groups
)

contact_matrix
```

Next we'll convert the contact matrix to a next generation matrix, with a specified reproduction number of 2.5

```{r calibrate-bgm}
# convert to next-generation matrix, with the specified reproduction number
ngm <- calibrate_ngm(ngm_unscaled = contact_matrix, R = 2.5)
ngm
```

Now let's simulate some cases and convert this to a matrix

```{r cases-matrix}
cases <- sim_cases(n_cases = 7, n_groups = n_groups)

cases

cases_matrix <- cases_to_matrix(cases = cases, n_groups = n_groups)

cases_matrix
```

And now let's simulate multiple generations of cases

```{r sim}
case_counts <- project(ngm = ngm,
                       infections_matrix = cases_matrix,
                       n_days_project = 10)

case_counts

rowSums(case_counts)
```
